### ISSUE TITLE
Issue modifying spec.cluster_group_name

### ISSUE THREAD

**Issue by ysineil** [vmware/terraform-provider-tanzu-mission-control#364] opened 2023-12-28 19:29 UTC
### Describe the bug

When adjusting spec.cluster_group_name from one group to another, the action times out and does not complete. In our case, we had hard coded cluster_group_name = "default" and when making it more dynamic, it failed. New cluster creation with the same group definition works.

main.tf section:

```
resource "tanzu-mission-control_tanzu_kubernetes_cluster" "tkgs_cluster" {
  management_cluster_name = var.management_cluster
  provisioner_name = var.provisioner
  name = var.name

  spec {
    cluster_group_name = "${var.location}"

    topology {
      version = replace("${var.k8s_version}", "&#43;", "+")
      cluster_class = "tanzukubernetescluster"
      cluster_variables = jsonencode(local.tkgs_cluster_variables)

      control_plane {
        replicas = 3

        os_image {
          name = "${var.os_image}"
          version = "3"
          arch = "amd64"
        }
      }
      
      nodepool {
        name = "default-nodepool-a"
        description = "tkgs workload nodepool"
      
        spec {
          worker_class = "node-pool"
          replicas = 3
          overrides = jsonencode(local.tkgs_cluster_variables)
          failure_domain = "${var.location}-zone-a"
      
          os_image {
            name = "${var.os_image}"
            version = "3"
            arch = "amd64"
          }
        }
      }

      nodepool {
        name = "default-nodepool-b"
        description = "tkgs workload nodepool"
      
        spec {
          worker_class = "node-pool"
          replicas = 3
          overrides = jsonencode(local.tkgs_cluster_variables)
          failure_domain = "${var.location}-zone-b"
      
          os_image {
            name = "${var.os_image}"
            version = "3"
            arch    = "amd64"
          }
        }
      }
      
      nodepool {
        name        = "default-nodepool-c"
        description = "tkgs workload nodepool"
      
        spec {
          worker_class   = "node-pool"
          replicas       = 3
          overrides      = jsonencode(local.tkgs_cluster_variables)
          failure_domain = "${var.location}-zone-c"
      
          os_image {
            name    = "${var.os_image}"
            version = "3"
            arch    = "amd64"
          }
        }
      }   

      network {
        pod_cidr_blocks = [
          "172.20.0.0/16",
        ]
        service_cidr_blocks = [
          "10.96.0.0/16",
        ]
        service_domain = "cluster.local"
      }
    }
  }

  timeout_policy {
    timeout             = 60
    wait_for_kubeconfig = true
    fail_on_timeout     = true
  }
}`
```

### Reproduction steps

1. Adjust spec.cluster_group_name and apply change.

### Expected behavior

Cluster group to update

**Comment by Axpz** [comment] 2024-01-04 15:20
Hi @ysineil, @ramya-bangera, I cann't reproduce this issue, please let me know if there is something I missed, and please find my reproduce steps:

1. Created a cluster and update the cluster_group_name
```
# tanzu-mission-control_tanzu_kubernetes_cluster.tkgs_cluster will be updated in-place
  ~ resource "tanzu-mission-control_tanzu_kubernetes_cluster" "tkgs_cluster" {
        id                      = "tf-mc/testns/tfu-100"
        name                    = "tfu-100"
        # (2 unchanged attributes hidden)

      ~ spec {
          ~ cluster_group_name = "default" -> "demo-cluster-group"
            # (2 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
```

2. After Entered yes, succeeded with terraform apply
`Apply complete! Resources: 1 added, 1 changed, 0 destroyed.`
3. Started another terraform plan, and get output
```
terraform plan                                                                                                
data.tanzu-mission-control_cluster_class.tkc-cc: Reading...
tanzu-mission-control_tanzu_kubernetes_cluster.tkgs_cluster: Refreshing state... [id=tf-mc/testns/tfu-100]
data.tanzu-mission-control_cluster_class.tkc-cc: Read complete after 3s [id=tf-mc/testns/tanzukubernetescluster]
local_file.foo: Refreshing state... [id=618be9bcf5d1abd28679479ecf8d535be5acc655]

No changes. Your infrastructure matches the configuration.
```

**Comment by Axpz** [comment] 2024-01-05 10:31
Oh, forget to mention, I am reproducing this issue with single control_plane, let me start a test with high-available mode.
And this is my state file
> {
  "version": 4,
  "terraform_version": "1.5.2",
  "serial": 7,
  "lineage": "f343d17f-0be0-31f8-8416-8fd300f5206f",
  "outputs": {
    "cluster_class_variables_schema": {
      "value": "{\"TKR_DATA\":{\"additionalProperties\":{\"properties\":{\"kubernetesSpec\":{\"properties\":{\"coredns\":{\"properties\":{\"imageTag\":{\"type\":\"string\"}},\"type\":\"object\"},\"etcd\":{\"properties\":{\"imageTag\":{\"type\":\"string\"}},\"type\":\"object\"},\"imageRepository\":{\"type\":\"string\"},\"version\":{\"type\":\"string\"}},\"type\":\"object\"},\"labels\":{\"additionalProperties\":{\"type\":\"string\"},\"type\":\"object\"},\"osImageRef\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"type\":\"object\"},\"clusterEncryptionConfigYaml\":{\"type\":\"string\"},\"controlPlaneCertificateRotation\":{\"default\":{\"activate\":false},\"properties\":{\"activate\":{\"default\":true,\"type\":\"boolean\"},\"daysBefore\":{\"default\":90,\"format\":\"int32\",\"minimum\":7,\"type\":\"integer\"}},\"type\":\"object\"},\"controlPlaneVolumes\":{\"items\":{\"properties\":{\"capacity\":{\"properties\":{\"storage\":{\"type\":\"string\"}},\"type\":\"object\"},\"mountPath\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"defaultRegistrySecret\":{\"properties\":{\"data\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"namespace\":{\"type\":\"string\"}},\"type\":\"object\"},\"defaultStorageClass\":{\"type\":\"string\"},\"defaultVolumeSnapshotClass\":{\"type\":\"string\"},\"extensionCert\":{\"properties\":{\"contentSecret\":{\"properties\":{\"key\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"nodePoolLabels\":{\"items\":{\"properties\":{\"key\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"nodePoolTaints\":{\"items\":{\"properties\":{\"effect\":{\"type\":\"string\"},\"key\":{\"type\":\"string\"},\"timeAdded\":{\"type\":\"integer\"},\"value\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"nodePoolVolumes\":{\"items\":{\"properties\":{\"capacity\":{\"properties\":{\"storage\":{\"type\":\"string\"}},\"type\":\"object\"},\"mountPath\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"ntp\":{\"type\":\"string\"},\"proxy\":{\"properties\":{\"httpProxy\":{\"type\":\"string\"},\"httpsProxy\":{\"type\":\"string\"},\"noProxy\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"type\":\"object\"},\"storageClass\":{\"required\":true,\"type\":\"string\"},\"storageClasses\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"trust\":{\"properties\":{\"additionalTrustedCAs\":{\"items\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"}},\"type\":\"object\"},\"user\":{\"properties\":{\"passwordSecret\":{\"properties\":{\"key\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"type\":\"object\"},\"sshAuthorizedKey\":{\"type\":\"string\"}},\"type\":\"object\"},\"vmClass\":{\"required\":true,\"type\":\"string\"},\"volumeSnapshotClasses\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}}",
      "type": "string"
    },
    "cluster_class_variables_template": {
      "value": "{\"TKR_DATA\":{\"custom_key\":{\"kubernetesSpec\":{\"coredns\":{\"imageTag\":\"String\"},\"etcd\":{\"imageTag\":\"String\"},\"imageRepository\":\"String\",\"version\":\"String\"},\"labels\":{\"custom_key\":\"String\"},\"osImageRef\":{\"name\":\"String\"}}},\"clusterEncryptionConfigYaml\":\"String\",\"controlPlaneCertificateRotation\":{\"activate\":false,\"daysBefore\":7},\"controlPlaneVolumes\":[{\"capacity\":{\"storage\":\"String\"},\"mountPath\":\"String\",\"name\":\"String\",\"storageClass\":\"String\"}],\"defaultRegistrySecret\":{\"data\":\"String\",\"name\":\"String\",\"namespace\":\"String\"},\"defaultStorageClass\":\"String\",\"defaultVolumeSnapshotClass\":\"String\",\"extensionCert\":{\"contentSecret\":{\"key\":\"String\",\"name\":\"String\"}},\"nodePoolLabels\":[{\"key\":\"String\",\"value\":\"String\"}],\"nodePoolTaints\":[{\"effect\":\"String\",\"key\":\"String\",\"timeAdded\":1,\"value\":\"String\"}],\"nodePoolVolumes\":[{\"capacity\":{\"storage\":\"String\"},\"mountPath\":\"String\",\"name\":\"String\",\"storageClass\":\"String\"}],\"ntp\":\"String\",\"proxy\":{\"httpProxy\":\"String\",\"httpsProxy\":\"String\",\"noProxy\":[\"String\"]},\"storageClass\":\"String\",\"storageClasses\":[\"String\"],\"trust\":{\"additionalTrustedCAs\":[{\"name\":\"String\"}]},\"user\":{\"passwordSecret\":{\"key\":\"String\",\"name\":\"String\"},\"sshAuthorizedKey\":\"String\"},\"vmClass\":\"String\",\"volumeSnapshotClasses\":[\"String\"]}",
      "type": "string"
    }
  },
  "resources": [
    {
      "mode": "data",
      "type": "tanzu-mission-control_cluster_class",
      "name": "tkc-cc",
      "provider": "provider[\"vmware/dev/tanzu-mission-control\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "tf-mc/testns/tanzukubernetescluster",
            "management_cluster_name": "tf-mc",
            "name": "tanzukubernetescluster",
            "provisioner_name": "testns",
            "variables_schema": "{\"TKR_DATA\":{\"additionalProperties\":{\"properties\":{\"kubernetesSpec\":{\"properties\":{\"coredns\":{\"properties\":{\"imageTag\":{\"type\":\"string\"}},\"type\":\"object\"},\"etcd\":{\"properties\":{\"imageTag\":{\"type\":\"string\"}},\"type\":\"object\"},\"imageRepository\":{\"type\":\"string\"},\"version\":{\"type\":\"string\"}},\"type\":\"object\"},\"labels\":{\"additionalProperties\":{\"type\":\"string\"},\"type\":\"object\"},\"osImageRef\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"type\":\"object\"},\"clusterEncryptionConfigYaml\":{\"type\":\"string\"},\"controlPlaneCertificateRotation\":{\"default\":{\"activate\":false},\"properties\":{\"activate\":{\"default\":true,\"type\":\"boolean\"},\"daysBefore\":{\"default\":90,\"format\":\"int32\",\"minimum\":7,\"type\":\"integer\"}},\"type\":\"object\"},\"controlPlaneVolumes\":{\"items\":{\"properties\":{\"capacity\":{\"properties\":{\"storage\":{\"type\":\"string\"}},\"type\":\"object\"},\"mountPath\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"defaultRegistrySecret\":{\"properties\":{\"data\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"namespace\":{\"type\":\"string\"}},\"type\":\"object\"},\"defaultStorageClass\":{\"type\":\"string\"},\"defaultVolumeSnapshotClass\":{\"type\":\"string\"},\"extensionCert\":{\"properties\":{\"contentSecret\":{\"properties\":{\"key\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"nodePoolLabels\":{\"items\":{\"properties\":{\"key\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"nodePoolTaints\":{\"items\":{\"properties\":{\"effect\":{\"type\":\"string\"},\"key\":{\"type\":\"string\"},\"timeAdded\":{\"type\":\"integer\"},\"value\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"nodePoolVolumes\":{\"items\":{\"properties\":{\"capacity\":{\"properties\":{\"storage\":{\"type\":\"string\"}},\"type\":\"object\"},\"mountPath\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"ntp\":{\"type\":\"string\"},\"proxy\":{\"properties\":{\"httpProxy\":{\"type\":\"string\"},\"httpsProxy\":{\"type\":\"string\"},\"noProxy\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"type\":\"object\"},\"storageClass\":{\"required\":true,\"type\":\"string\"},\"storageClasses\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"trust\":{\"properties\":{\"additionalTrustedCAs\":{\"items\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"}},\"type\":\"object\"},\"user\":{\"properties\":{\"passwordSecret\":{\"properties\":{\"key\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"type\":\"object\"},\"sshAuthorizedKey\":{\"type\":\"string\"}},\"type\":\"object\"},\"vmClass\":{\"required\":true,\"type\":\"string\"},\"volumeSnapshotClasses\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}}",
            "variables_template": "{\"TKR_DATA\":{\"custom_key\":{\"kubernetesSpec\":{\"coredns\":{\"imageTag\":\"String\"},\"etcd\":{\"imageTag\":\"String\"},\"imageRepository\":\"String\",\"version\":\"String\"},\"labels\":{\"custom_key\":\"String\"},\"osImageRef\":{\"name\":\"String\"}}},\"clusterEncryptionConfigYaml\":\"String\",\"controlPlaneCertificateRotation\":{\"activate\":false,\"daysBefore\":7},\"controlPlaneVolumes\":[{\"capacity\":{\"storage\":\"String\"},\"mountPath\":\"String\",\"name\":\"String\",\"storageClass\":\"String\"}],\"defaultRegistrySecret\":{\"data\":\"String\",\"name\":\"String\",\"namespace\":\"String\"},\"defaultStorageClass\":\"String\",\"defaultVolumeSnapshotClass\":\"String\",\"extensionCert\":{\"contentSecret\":{\"key\":\"String\",\"name\":\"String\"}},\"nodePoolLabels\":[{\"key\":\"String\",\"value\":\"String\"}],\"nodePoolTaints\":[{\"effect\":\"String\",\"key\":\"String\",\"timeAdded\":1,\"value\":\"String\"}],\"nodePoolVolumes\":[{\"capacity\":{\"storage\":\"String\"},\"mountPath\":\"String\",\"name\":\"String\",\"storageClass\":\"String\"}],\"ntp\":\"String\",\"proxy\":{\"httpProxy\":\"String\",\"httpsProxy\":\"String\",\"noProxy\":[\"String\"]},\"storageClass\":\"String\",\"storageClasses\":[\"String\"],\"trust\":{\"additionalTrustedCAs\":[{\"name\":\"String\"}]},\"user\":{\"passwordSecret\":{\"key\":\"String\",\"name\":\"String\"},\"sshAuthorizedKey\":\"String\"},\"vmClass\":\"String\",\"volumeSnapshotClasses\":[\"String\"]}",
            "worker_classes": [
              "node-pool"
            ]
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "mode": "managed",
      "type": "tanzu-mission-control_tanzu_kubernetes_cluster",
      "name": "tkgs_cluster",
      "provider": "provider[\"vmware/dev/tanzu-mission-control\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "tf-mc/testns/tfu-100",
            "management_cluster_name": "tf-mc",
            "meta": [
              {
                "annotations": {
                  "tmc-internal-uid": "c:01HKC2D5C4VE6WVN1D8D05TX54"
                },
                "description": "",
                "labels": {
                  "tmc.cloud.vmware.com/creator": "zxianping"
                },
                "resource_version": "873",
                "uid": "tkc:8c0930e9-e0fa-4b4b-ac5f-e13dcfc5883d"
              }
            ],
            "name": "tfu-100",
            "provisioner_name": "testns",
            "spec": [
              {
                "cluster_group_name": "demo-cluster-group",
                "image_registry": "",
                "kubeconfig": "YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNMmFrTkRRV1JMWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkpNRTFFUlhkT1ZFRXhUWHByZWs0eGIxaEVWRTB3VFVSRmQwMXFRVEZPUkZGNlRqRnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVFVJd0NtNW5kbmxNTTNaUmMyODRjV1JhUW5WSk9WbGlMM1JuU2xod1Ftd3diR3hxVmt4cFJWZElTVEl6TlZoMllWRlZkMlI0ZW5kdFpYWndRM2czTlU0MGNrY0tiREZuYm1sVmNXMXNjVVZSVkdvNFZEaHRjVWRXVVNzelZHUmpOVGRNZVVGelVtMXliVlpSTDBOMFUxazBjbGQxTkZWclQzUlZaRlpTY2xsblpVaDJhQW81TjJneFZqVnpTRVpXZFRGTmJXMDNUWEkwWVZoM05tTkpRako1UW01VU0zZzBaMk56YlRSMFpVSnliR05uWlVaeU1HWnZTMGw0ZW5JNVNsUnFWR1pXQ2tWd0wzQXlRbFJ0T1hBdkswOW5hak5aYzJaMVYwRm1hMmxqTVZJdksydDRRelpYYkdKWWRUa3pjV0pyWkdKa05sZEVTbmxKUkRaT2JsTXdLemRDWlVrS2IxUmpZblJZWTBVdmRESnNiV2hFUzNKeVIxSXpNbGh6TDJwVEsyZ3JhRnBYT1V4TE9HSnphekpHVVdwV2NsbDRlVUlyZUd0cGVXdHNabXBMZDFST1dnbzNia3RwWm04MmFFUnVlR0V2WVVoMFQwZE5RMEYzUlVGQllVNUdUVVZOZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVSkpSMEV4VldSRmQwVkNDaTkzVVVsTlFWbENRV1k0UTBGUlFYZElVVmxFVmxJd1QwSkNXVVZHUkhWWU1YWkJVV2d3Vkc1UFMzZFVOM1JxTDFCb1JqZEJZakZRVFVFd1IwTlRjVWNLVTBsaU0wUlJSVUpEZDFWQlFUUkpRa0ZSUVRGaVRVeDNiazlUUzFCcVVESkxZV2xsVmtkTGJEVkNjemgyYm5GRlRFeG9XRXA0TjFwM1ZqVlNOVzV4ZUFwMU9XUklWamh4U1ZBeVRFOUNibTlGYjFrdmNpdHVkVEJHZFV4SWJ6aFdNRVZpVm5KVlNTOHJRV281YkdzcmRUUlFPSGd2VUdGdVJrSkthR3htVkVaMkNtVk1abFZCVm5CMmNXcHlkM1Z5V2sxa1NFRmtPV3h1UTJFdk1qTkRSemQzWms1emFGbzJSVGMzVW5kR01FZG5UWEJqZVdwaWVrRlFSSFp1TUhoNFVXc0tUSFYxVWxRelFVaENXbkJJUldSNUszZHBRbTVvTldGSFNrTnZWa05FZVZWVk1Fc3haMnRxT0VkcFkyMVJlbXBPTkZvM1JFTlpNV3BzTDNOalQwZHhXUXBQTkZkelVuTm1TVUZZWlZvMVRWWkNURE55ZGtrMFptRm9RMkpxTlVOTGJXbEVVVTFZV20xeU9UaEhVMVF4UkZoMFpVWjJWRUZyV2poVWFUSTNjVk5ZQ25sWFNHOUtUM2xzYUM5TmRXZFljMGh2ZUdONk9GcEtWVUZJSzBwalYyMXhURzVFUVd4Nk0wSUtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly8xOTIuMTY4LjAuMzo2NDQzCiAgbmFtZTogdGZ1LTEwMApjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogdGZ1LTEwMAogICAgbmFtZXNwYWNlOiBkZWZhdWx0CiAgICB1c2VyOiB0ZnUtMTAwCiAgbmFtZTogdGZ1LTEwMApjdXJyZW50LWNvbnRleHQ6IHRmdS0xMDAKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiB0ZnUtMTAwCiAgdXNlcjoKICAgIGV4ZWM6CiAgICAgIGFwaVZlcnNpb246IGNsaWVudC5hdXRoZW50aWNhdGlvbi5rOHMuaW8vdjFiZXRhMQogICAgICBhcmdzOgogICAgICAtIHRtYwogICAgICAtIGNsdXN0ZXIKICAgICAgLSBnZW5lcmF0ZS10b2tlbgogICAgICBjb21tYW5kOiB0YW56dQogICAgICBlbnY6CiAgICAgIC0gbmFtZTogQ0xVU1RFUl9VSUQKICAgICAgICB2YWx1ZTogYzowMUhLQzJENUM0VkU2V1ZOMUQ4RDA1VFg1NAogICAgICAtIG5hbWU6IENMVVNURVJfUklEX1YyCiAgICAgICAgdmFsdWU6IHJpZDpjOmJjMjc2MDhiLTQ4MDktNGNhYy05ZTA0LTc3ODgwMzk2M2RhMjp0Zi1tYzp0ZXN0bnM6dGZ1LTEwMAogICAgICAtIG5hbWU6IENMVVNURVJfRU5EUE9JTlQKICAgICAgICB2YWx1ZTogaHR0cHM6Ly8xOTIuMTY4LjAuMzo2NDQzCiAgICAgIC0gbmFtZTogQ0xVU1RFUl9DQV9CVU5ETEUKICAgICAgICB2YWx1ZTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTTJha05EUVdSTFowRjNTVUpCWjBsQ1FVUkJUa0puYTNGb2EybEhPWGN3UWtGUmMwWkJSRUZXVFZKTmQwVlJXVVJXVVZGRVJYZHdjbVJYU213S1kyMDFiR1JIVm5wTlFqUllSRlJKTUUxRVJYZE9WRUV4VFhwcmVrNHhiMWhFVkUwd1RVUkZkMDFxUVRGT1JGRjZUakZ2ZDBaVVJWUk5Ra1ZIUVRGVlJRcEJlRTFMWVROV2FWcFlTblZhV0ZKc1kzcERRMEZUU1hkRVVWbEtTMjlhU1doMlkwNUJVVVZDUWxGQlJHZG5SVkJCUkVORFFWRnZRMmRuUlVKQlRVSXdDbTVuZG5sTU0zWlJjMjg0Y1dSYVFuVkpPVmxpTDNSblNsaHdRbXd3Ykd4cVZreHBSVmRJU1RJek5WaDJZVkZWZDJSNGVuZHRaWFp3UTNnM05VNDBja2NLYkRGbmJtbFZjVzFzY1VWUlZHbzRWRGh0Y1VkV1VTc3pWR1JqTlRkTWVVRnpVbTF5YlZaUkwwTjBVMWswY2xkMU5GVnJUM1JWWkZaU2NsbG5aVWgyYUFvNU4yZ3hWalZ6U0VaV2RURk5iVzAzVFhJMFlWaDNObU5KUWpKNVFtNVVNM2cwWjJOemJUUjBaVUp5YkdOblpVWnlNR1p2UzBsNGVuSTVTbFJxVkdaV0NrVndMM0F5UWxSdE9YQXZLMDluYWpOWmMyWjFWMEZtYTJsak1WSXZLMnQ0UXpaWGJHSllkVGt6Y1dKclpHSmtObGRFU25sSlJEWk9ibE13S3pkQ1pVa0tiMVJqWW5SWVkwVXZkREpzYldoRVMzSnlSMUl6TWxoekwycFRLMmdyYUZwWE9VeExPR0p6YXpKR1VXcFdjbGw0ZVVJcmVHdHBlV3RzWm1wTGQxUk9XZ28zYmt0cFptODJhRVJ1ZUdFdllVaDBUMGROUTBGM1JVRkJZVTVHVFVWTmQwUm5XVVJXVWpCUVFWRklMMEpCVVVSQlowdHJUVUpKUjBFeFZXUkZkMFZDQ2k5M1VVbE5RVmxDUVdZNFEwRlJRWGRJVVZsRVZsSXdUMEpDV1VWR1JIVllNWFpCVVdnd1ZHNVBTM2RVTjNScUwxQm9SamRCWWpGUVRVRXdSME5UY1VjS1UwbGlNMFJSUlVKRGQxVkJRVFJKUWtGUlFURmlUVXgzYms5VFMxQnFVREpMWVdsbFZrZExiRFZDY3poMmJuRkZURXhvV0VwNE4xcDNWalZTTlc1eGVBcDFPV1JJVmpoeFNWQXlURTlDYm05RmIxa3ZjaXR1ZFRCR2RVeEliemhXTUVWaVZuSlZTUzhyUVdvNWJHc3JkVFJRT0hndlVHRnVSa0pLYUd4bVZFWjJDbVZNWmxWQlZuQjJjV3B5ZDNWeVdrMWtTRUZrT1d4dVEyRXZNak5EUnpkM1prNXphRm8yUlRjM1VuZEdNRWRuVFhCamVXcGlla0ZRUkhadU1IaDRVV3NLVEhWMVVsUXpRVWhDV25CSVJXUjVLM2RwUW01b05XRkhTa052VmtORWVWVlZNRXN4WjJ0cU9FZHBZMjFSZW1wT05GbzNSRU5aTVdwc0wzTmpUMGR4V1FwUE5GZHpVbk5tU1VGWVpWbzFUVlpDVEROeWRrazBabUZvUTJKcU5VTkxiV2xFVVUxWVdtMXlPVGhIVTFReFJGaDBaVVoyVkVGcldqaFVhVEkzY1ZOWUNubFhTRzlLVDNsc2FDOU5kV2RZYzBodmVHTjZPRnBLVlVGSUswcGpWMjF4VEc1RVFXeDZNMElLTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUW89CiAgICAgIC0gbmFtZTogVE1DX0VOVklST05NRU5UCiAgICAgICAgdmFsdWU6IHVuc3RhYmxlCiAgICAgIC0gbmFtZTogVE1DX0VORFBPSU5UCiAgICAgICAgdmFsdWU6IHp4cC50bWMtZGV2LmNsb3VkLnZtd2FyZS5jb20KICAgICAgcHJvdmlkZUNsdXN0ZXJJbmZvOiBmYWxzZQo=",
                "proxy_name": "",
                "tmc_managed": true,
                "topology": [
                  {
                    "cluster_class": "tanzukubernetescluster",
                    "cluster_variables": "{\"controlPlaneCertificateRotation\":{\"activate\":true,\"daysBefore\":31},\"defaultStorageClass\":\"tkgs-k8s-obj-policy\",\"defaultVolumeSnapshotClass\":\"volumesnapshotclass-delete\",\"nodePoolLabels\":[],\"nodePoolVolumes\":[{\"capacity\":{\"storage\":\"20G\"},\"mountPath\":\"/var/lib/containerd\",\"name\":\"containerd\",\"storageClass\":\"tkgs-k8s-obj-policy\"},{\"capacity\":{\"storage\":\"20G\"},\"mountPath\":\"/var/lib/kubelet\",\"name\":\"kubelet\",\"storageClass\":\"tkgs-k8s-obj-policy\"}],\"storageClass\":\"tkgs-k8s-obj-policy\",\"storageClasses\":[\"tkgs-k8s-obj-policy\"],\"vmClass\":\"best-effort-medium\"}",
                    "control_plane": [
                      {
                        "meta": [],
                        "os_image": [
                          {
                            "arch": "amd64",
                            "name": "photon",
                            "version": "3"
                          }
                        ],
                        "replicas": 1
                      }
                    ],
                    "core_addon": [],
                    "network": [
                      {
                        "pod_cidr_blocks": [
                          "100.96.0.0/11"
                        ],
                        "service_cidr_blocks": [
                          "100.64.0.0/13"
                        ],
                        "service_domain": "cluster.local"
                      }
                    ],
                    "nodepool": [
                      {
                        "description": "simple small md",
                        "name": "md-0",
                        "spec": [
                          {
                            "failure_domain": "",
                            "meta": [],
                            "os_image": [
                              {
                                "arch": "amd64",
                                "name": "photon",
                                "version": "3"
                              }
                            ],
                            "overrides": "{\"storageClass\":\"tkgs-k8s-obj-policy\",\"vmClass\":\"best-effort-medium\"}",
                            "replicas": 1,
                            "worker_class": "node-pool"
                          }
                        ]
                      }
                    ],
                    "version": "v1.23.8+vmware.2-tkg.2-zshippable"
                  }
                ]
              }
            ],
            "timeout_policy": []
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
  ],
  "check_results": null
}

**Comment by Axpz** [comment] 2024-01-11 01:39
Hi @ysineil, we have been starting to fix this issue from backend (TMC `UPDATE` API), hoping this can be done in next week considering the test and promotion.

**Comment by Axpz** [comment] 2024-01-31 04:39
Hi @ysineil, this issue have been fixed from TMC side, again sorry for some delay because of tech issue.
You can take a retry and if you have any questions just feel free to let us know, thanks!

**Comment by Axpz** [comment] 2024-02-05 09:05
Hi @ysineil, there is no change from terraform side, can I close this if there is no other questions.

**Comment by ysineil** [comment] 2024-02-05 22:05
changes look like they're working as expected now, thank you!

**Comment by vmw-vjn** [comment] 2024-02-06 06:03
Thank you for confirming, closing issue.

**Closed by vmw-vjn** 2024-02-06 06:03 UTC
Labels: bug
