### ISSUE TITLE
`ready_wait_timeout` is not respected for EKS anymore.

### ISSUE THREAD

**Issue by asutoshpalai** [vmware/terraform-provider-tanzu-mission-control#233] opened 2023-08-16 18:32 UTC
### Describe the bug

We have received user complaints that `ready_wait_timeout` is no longer respected for EKS cluster resources.

My primary suspect is https://github.com/vmware/terraform-provider-tanzu-mission-control/commit/6dc94a40f18279c19e93cde070e1dacaecb804d8#diff-051c56ef0c686384f313ea8c9a884824f0f771460874096100e8d33e9b2ed00dR84-R86. This was added to fix the diff issue when importing an existing EKS cluster.

If this does turn out to be the culprit here, we should remove this and just set the value of `ready_wait_timeout` back in the resource returned by import and data ready (maybe).

### Reproduction steps

1. Write an EKS cluster resource TF file with `ready_wait_timeout` as 20 mins.
2. Apply the resource file.
3. The cluster creation finishes in about 3m (the default value) even if `ready_wait_timeout` is 20 mins

### Expected behavior

Terrafrom creation step should wait for 20 mins or the cluster being created before finishing,

**Comment by ramya-bangera** [comment] 2023-08-18 05:22
@asutoshpalai - Isn't this issue is duplicate of [Issue#181](https://github.com/vmware/terraform-provider-tanzu-mission-control/issues/181) ? Or is there some other issue which is being tracked here?

**Comment by ramya-bangera** [comment] 2023-10-11 01:52
I am resolving this as a fix for this issue is already released.

**Closed by ramya-bangera** 2023-10-11 01:52 UTC
Labels: bug
